<pre class='metadata'>
Title: Policy Catalog (PolicyCAT) specification
Shortname: PolicyCAT
Level: none
Status: LD
Editor: Beatriz Esteves, Ghent University - imec http://idlab.ugent.be/, beatriz.esteves@ugent.be
Abstract: The Policy Catalog (PolicyCAT) specification aims to define a standardised format for collections of policies, focusing in the management, description, and reusability of different types of access and usage control policies.
Markup Shorthands: markdown yes, css no
URL: https://spec.knows.idlab.ugent.be/PolicyCAT/latest/
Canonical URL: _ORCHESTRATOR_CURRENT_BUILD_FULL_LINK_
Previous Version: _ORCHESTRATOR_PREVIOUS_BUILD_FULL_LINK_
Repository: https://github.com/KNowledgeOnWebScale/policyCAT
!License: <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA-4.0</a>
</pre>

<p boilerplate="copyright">
  <!-- This document is made available under the CC-BY-SA-4.0 License. -->
</p>

<pre class=biblio> 
{
  "ODRL-formal-semantics": {
    "href": "https://w3c.github.io/odrl/formal-semantics/",
    "title": "ODRL Formal Semantics",
    "authors": [
        "Nicoletta Fornara",
        "Víctor Rodríguez-Doncel",
        "Beatriz Esteves",
        "Simon Steyskal",
        "Benedict Whittam Smith"
		]
  },
  "DPV": {
    "href": "https://w3id.org/dpv",
    "title": "Data Privacy Vocabulary (DPV)",
    "authors": [
      "Beatriz Esteves",
      "Delaram Golpayegani",
      "Georg P. Krog",
      "Harshvardhan J. Pandit",
      "Julian Flake",
      "Paul Ryan"
    ]
  }
}
</pre>

Introd­uction {#introduction}
============================

The Data Catalog Vocabulary (DCAT) [[!VOCAB-DCAT-3]] is a W3C Recommendation that provides a standardised, machine-readable way to express information related to data catalogs published on the Web.
It enables data publishers to describe datasets and data services in a catalog using a standard model and vocabulary that facilitates the consumption and aggregation of metadata from multiple catalogs.

While this standard focuses on the cataloguing of datasets and related data services, it can be extended to incorporate other types of resources via the `dcat:Resource` class, which is an extension point for defining a catalog of any kind of resources.
As such, in this specification, we extend the DCAT standard with concepts to define catalogs of data usage conditions, i.e., [=Policies=].

In this context, the Policy Catalog (PolicyCAT) specification aims to define a standardised format for collections of policies, focusing in the management, description, and reusability of different types of access and usage control policies.
These catalogs can then include metadata such as the name, description, temporal stamps, and include references to specific data elements, purposes, and user groups involved in each policy.
Moreover, by implementing this specification, data publishers and consumers allow individuals and companies to define different data usages conditions profiles and apply them to specific types of data.

Besides DCAT, the DCMI Metadata Terms Recommendation [[!DCTERMS]] is also used to specify catalog metadata such as issuance and update dates, as well as information related to policy publishers and creators.

## Terminology ## {#terminology}

The following terms are used to describe concepts in this specification. 

<dl>
  <dt><dfn>Policies</dfn></dt>
  <dd>Data usage conditions that can be associated with any resource. Policies can include permissive, prohibitive and obligatory rules and can be limited by constraints, such as temporal or spatial restrictions, and duties, such as making a payment or a deleting an asset after using it.</dd>

  <dt><dfn>Policy Catalog</dfn></dt>
  <dd>A collection of policies, including metadata related to such policies.</dd>
</dl>

## Namespaces ## {#namespaces}

Commonly used namespace prefixes used in this specification:
```turtle
@prefix dcat:          <http://www.w3.org/ns/dcat#> .
@prefix dcterms:       <http://purl.org/dc/terms/> .
@prefix dpv:            <https://w3id.org/dpv#> .
@prefix ex:            <http://example.org/> .
@prefix foaf:          <http://xmlns.com/foaf/0.1/> .
@prefix ieee-7012:     <https://w3id.org/dpv/standards/ieee/7012#> .
@prefix odrl:          <http://www.w3.org/ns/odrl/2/> .
@prefix owl:           <http://www.w3.org/2002/07/owl#> .
@prefix policyCAT:     <https://w3id.org/force/policyCAT#> .
@prefix rdf:           <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:          <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sector-health: <https://w3id.org/dpv/sector/health>
@prefix skos:          <http://www.w3.org/2004/02/skos/core#> .
@prefix xsd:           <http://www.w3.org/2001/XMLSchema#> .
```

Main Entities {#main-entities}
==============================

## Catalog ## {#catalog}

`dcat:Catalog` is used to record metadata related to a collection of resources, including descriptions, temporal stamps, information about the entity that publishes the catalog, and so on. As such, in the context of this specification, it is used to record metadata related to a catalog of policies. A description of a catalog is shown below:

```turtle
ex:policy-catalog-001 a dcat:Catalog ;
  dcterms:title "Policy Catalog 001"@en ;
  dcterms:description "Catalog published by policy provider X, in English, with policies related to health data sharing"@en ;
  dcterms:publisher ex:policy-provider-x ;
  foaf:homepage <http://example.org/catalog/policy> ;
  dcterms:language <http://id.loc.gov/vocabulary/iso639-1/en>  ;
  dcat:themeTaxonomy ex:health-data ;
  policyCAT:policy ex:policy-001 , ex:policy-002 , ex:policy-003 .
```

The [policyCAT:policy](#policy-property) property is defined in this specification to associate a `dcat:Catalog` with the corresponding policies, i.e., [policyCAT:Policy](#policy-class).

Moreover, the following properties should be used to describe the catalog:
- `dcterms:title` and `dcterms:description` to specify the name and provide a description of the catalog;
- `dcterms:publisher` to identify the publisher of the catalog;
- `foaf:homepage` to associate a catalog with a Web page where it is available;
- `dcterms:language` to describe the language of the policies in the catalog;
- `dcat:themeTaxonomy` to classify the catalog's policies according to a set of domains.

In this context, the `dcat:themeTaxonomy` property can be used to include references to specific data elements, purposes, and user groups involved in the policies of the catalog, e.g., using the SKOS vocabulary [[!SKOS-REFERENCE]] to describe them. For instance, the example below defines `ex:health-records` and `ex:healthcare-provision` as being part of the set of domains of the theme taxonomy `ex:health-data` that describes the `ex:policy-catalog-001` policy catalog. The DPV [[!DPV]] specification and its extensions contain terms to describe data, purposes, and other taxonomies, that can be used to describe domains related to the policies.

```turtle
ex:health-data a skos:ConceptScheme ;
  skos:prefLabel "A set of domains to classify the health data sharing policies in the catalog"@en .

ex:health-records a skos:Concept, sector-health:EHRData ;
  skos:inScheme ex:health-data ;
  skos:prefLabel "Health record data"@en .

ex:healthcare-provision a skos:Concept, sector-health:ServiceProvision ;
  skos:inScheme ex:health-data ;
  skos:prefLabel "Healthcare service provision"@en .
```

Note: `odrl:hasPolicy` can be used to associate the catalog with its usage conditions using an ODRL conformant policy [[!ODRL-MODEL]]. Similarly, it can also be used for resources with the same goal.

Note: Versioning of catalogs can be done using `dcat:version`, `dcat:previousVersion`, `dcat:hasVersion`, and `dcat:hasCurrentVersion`. Analogously, it can also be used to version resources such as policies.

## Policies ## {#policy-resource}

The catalog lists each of its policies, i.e., `policyCAT:Policy`, a subclass of `dcat:Resource`, via the `policyCAT:policy` property, a subclass of `dcat:resource`. A possible description of a policy resource using DCAT is shown below:

```turtle
ex:policy-001 a policyCAT:Policy ;
  dcterms:title "Policy 001"@en ;
  dcterms:description "Policy 001"@en ;
  dcterms:issued "2011-12-05"^^xsd:date ;
  dcterms:modified "2011-12-15"^^xsd:date ;
  dcterms:creator ex:employee-001 ;
  dcterms:publisher ex:lab ;
  dcat:contactPoint <http://example.org/employee-001/contact> ;
  dcterms:conformsTo <http://www.w3.org/ns/odrl/2/> ;
  dcterms:language <http://id.loc.gov/vocabulary/iso639-1/en> ;
  dcat:theme ex:health-records, ex:healthcare-provision ;
  dcat:distribution ex:policy-001-ttl .
```

The following properties should be used to describe the policy resource:
- `dcterms:title` and `dcterms:description` to specify the name and provide a description of the policy;
- The policy publication and revision dates are shown in `dcterms:issued` and `dcterms:modified`;
- `dcterms:accrualPeriodicity` can be used to represent the frequency of update of the policy;
- The temporal validity of the policy can be given using the `dcterms:temporal` property, defining a `dcterms:PeriodOfTime` as a closed interval indicated by `dcat:startDate` and `dcat:endDate`;
- `dcterms:creator` and `dcterms:publisher` should be used to define the entity responsible for producing the resource and the entity responsible for making the resource available, respectively;
- The `dcat:contactPoint` property can be used to provide the contact details of such entities;
- `dcterms:conformsTo` should be used to indicate the standard or specification that the policy representation conforms to, e.g., `ex:policy-001` states that the mentioned policy conforms to the ODRL standard [[!ODRL-MODEL]];
- `dcterms:language` should be used to describe the language of the policies;
- `dcat:theme` is used to describe the themes or domains related to the described policy.

For instance, `ex:policy-001` is classified under the domains represented by the relative IRI `ex:health-records` and `ex:healthcare-provision`, which are part of the concept scheme identified by the IRI `ex:health-data` that was used to describe the catalog domain.

Finally, different representations of the policy `ex:policy-001` can be linked using the [policyCAT:policyDistribution](#distribution-property) property. The example above includes a distribution in the `.ttl` format.

## Distribution ## {#distribution}

[policyCAT:PolicyDistribution](#distribution-class) represents an accessible form of a dataset such as a downloadable file.

```turtle
ex:policy-001-ttl a policyCAT:PolicyDistribution ;
  dcterms:title "TTL distribution of policy 001"@en ;
  dcterms:description "TTL distribution of policy 001"@en ;
  dcterms:issued "2011-12-05"^^xsd:date ;
  dcterms:modified "2011-12-15"^^xsd:date ;
  dcat:downloadURL <http://example.org/policy/001.ttl> ;
  dcat:mediaType <https://www.iana.org/assignments/media-types/text/turtle> .
```

The following properties should be used to describe the policy distribution:
- `dcterms:title` and `dcterms:description` to specify the name and provide a description of the distribution of the policy;
- `dcterms:issued` and `dcterms:modified` to add temporal aspects of the distribution;
- `dcat:downloadURL` should be used to provide the downloadable policy file in a given format, indicated via the `dcat:mediaType` property.

## Agents ## {#agents}

DCAT uses `foaf:Agent`, and its sub-classes `foaf:Person` (for people) and `foaf:Organization` (for government agencies or other entities) to represent entities that create and publish catalogs and their resources. The DPV [[!DPV]] specification can also be used to describe entities.

```turtle
ex:policy-provider-x a foaf:Organization, dpv:Organisation ;
  foaf:name "Policy Provider"@en ;
  dpv:hasName "Policy Provider"@en ;
  dpv:hasAddress "Street X, City Y"@en ;
  dpv:hasContact "policy-provider-x@email.org"@en .
```

Vocabulary specification {#vocabulary}
======================================

## Classes ## {#classes}

### Policy ### {#policy-class}

<pre class=simpledef>
IRI: [https://w3id.org/force/policyCAT#Policy](https://w3id.org/force/policyCAT#Policy)
Label: Policy
Type: [rdfs:Class](http://www.w3.org/2000/01/rdf-schema#Class), [owl:Class](http://www.w3.org/2002/07/owl#Class)
Definition: A resource that describes data access and usage conditions related to an asset, e.g., data or services.
Scope: To be used to catalog policies and their related metadata.
Subclass of: [rdfs:subClassOf](http://www.w3.org/2000/01/rdf-schema#subClassOf)
</pre>

### Policy Distribution ### {#distribution-class}

<pre class=simpledef>
IRI: [https://w3id.org/force/policyCAT#PolicyDistribution](https://w3id.org/force/policyCAT#PolicyDistribution)
Label: Policy Distribution
Type: [rdfs:Class](http://www.w3.org/2000/01/rdf-schema#Class), [owl:Class](http://www.w3.org/2002/07/owl#Class)
Definition: A specific representation of a policy, e.g, in `.ttl` format.
Scope: A policy might have several different distributions.
</pre>

## Properties ## {#classes}

### policy ### {#policy-property}

<pre class=simpledef>
IRI: [https://w3id.org/force/policyCAT#policy](https://w3id.org/force/policyCAT#policy)
Label: policy
Type: [rdf:Property](http://www.w3.org/1999/02/22-rdf-syntax-ns#Property), [owl:ObjectProperty](http://www.w3.org/2002/07/owl#ObjectProperty)
Definition: A policy that is listed in the catalog.
Domain: [dcat:Catalog](http://www.w3.org/ns/dcat#Catalog)
Range: [policyCAT:Policy](https://w3id.org/force/policyCAT#Policy)
</pre>

### policy distribution ### {#distribution-property}

<pre class=simpledef>
IRI: [https://w3id.org/force/policyCAT#policyDistribution](https://w3id.org/force/policyCAT#policyDistribution)
Label: policy distribution
Type: [rdf:Property](http://www.w3.org/1999/02/22-rdf-syntax-ns#Property), [owl:ObjectProperty](http://www.w3.org/2002/07/owl#ObjectProperty)
Definition: An available distribution of the policy.
Sub property of: [dcterms:relation](http://purl.org/dc/terms/relation)
Domain: [policyCAT:Policy](https://w3id.org/force/policyCAT#Policy)
Range: [policyCAT:PolicyDistribution](https://w3id.org/force/policyCAT#PolicyDistribution)
</pre>

Examples {#examples}
======================================

## Policy Catalog for IEEE 7012 Standard ## {#classes}

```turtle
ex:policy-catalog-ieee-7012 a dcat:Catalog ;
  dcterms:title "Policy Catalog for IEEE 7012 Standard"@en ;
  dcterms:description "Catalog with policies related to the IEEE 7012 Standard"@en ;
  dcterms:publisher ex:policy-provider-ieee-7012 ;
  foaf:homepage <https://github.com/coolharsh55/myterms> ;
  dcterms:language <http://id.loc.gov/vocabulary/iso639-1/en>  ;
  dcat:themeTaxonomy ex:ieee-7012-themes ;
  policyCAT:policy ex:SD-BASE, ex:SD-BASE-DP, ex:SD-BASE-A, ex:SD-BASE-A-DP, SD-BASE-AT,
    ex:SD-BASE-AT-DP, ex:SD-BASE-ATP, ex:SD-BASE-ATP-DP, SD-BASE-ATP-S3P,
    ex:SD-BASE-ATP-S3P-DP, ex:PDC-INTENT, ex:PDC-AI, ex:PDC-GOOD .

ex:policy-provider-ieee-7012 a foaf:Person ;
  dpv:hasContact "https://github.com/besteves4"@en .

ex:ieee-7012-themes a skos:ConceptScheme ;
  skos:prefLabel "A set of domains to classify the policies in the IEEE 7012 Standard"@en .

ex:SD-required a skos:Concept, ieee-7012:ServiceDelivery ;
  skos:inScheme ex:ieee-7012-themes ;
  skos:prefLabel "Service delivery is required"@en .

ex:DP-required a skos:Concept, ieee-7012:PortabilityRequired ;
  skos:inScheme ex:ieee-7012-themes ;
  skos:prefLabel "Data portability is required"@en .

ex:SD-BASE-DP a policyCAT:Policy ;
  dcterms:title "Policy SD-BASE-DP"@en ;
  dcterms:description "Policy that requires Service Delivery, with an obligation for Data Portability"@en ;
  dcterms:issued "2026-01-05"^^xsd:date ;
  dcterms:creator ex:policy-provider-ieee-7012 ;
  dcterms:publisher ex:policy-provider-ieee-7012 ;
  dcat:contactPoint <https://github.com/besteves4> ;
  dcterms:conformsTo <https://standards.ieee.org/ieee/7012/7192/> ;
  dcterms:language <http://id.loc.gov/vocabulary/iso639-1/en> ;
  dcat:theme eex:DP-required, ex:SD-required ;
  dcat:distribution ex:SD-BASE-DP-ttl .

ex:SD-BASE-DP-ttl a policyCAT:PolicyDistribution ;
  dcterms:title "TTL distribution of policy SD-BASE-DP"@en ;
  dcterms:description "TTL distribution of policy SD-BASE-DP"@en ;
  dcterms:issued "2026-01-05"^^xsd:date ;
  dcat:downloadURL <https://github.com/coolharsh55/myterms/blob/master/odrl-contracts/SD-BASE-ATP-DP.ttl> ;
  dcat:mediaType <https://www.iana.org/assignments/media-types/text/turtle> .
```
