<pre class='metadata'>
Title: Policy Catalog (PolicyCAT) specification
Shortname: PolicyCAT
Level: none
Status: LD
Editor: Beatriz Esteves, Ghent University - imec http://idlab.ugent.be/, beatriz.esteves@ugent.be
Abstract: The Policy Catalog (PolicyCAT) specification aims to define a standardised format for collections of policies, focusing in the management, description, and reusability of different types of access and usage control policies.
Markup Shorthands: markdown yes, css no
URL: https://spec.knows.idlab.ugent.be/PolicyCAT/latest/
Canonical URL: _ORCHESTRATOR_CURRENT_BUILD_FULL_LINK_
Previous Version: _ORCHESTRATOR_PREVIOUS_BUILD_FULL_LINK_
Repository: https://github.com/KNowledgeOnWebScale/policyCAT
!License: <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA-4.0</a>
</pre>

<p boilerplate="copyright">
  <!-- This document is made available under the CC-BY-SA-4.0 License. -->
</p>

<pre class=biblio> 
{"ODRL-formal-semantics": {
    "href": "https://w3c.github.io/odrl/formal-semantics/",
    "title": "ODRL Formal Semantics",
    "authors": [
        "Nicoletta Fornara",
        "Víctor Rodríguez-Doncel",
        "Beatriz Esteves",
        "Simon Steyskal",
        "Benedict Whittam Smith"
		]
    }
}
</pre>

Introd­uction {#introduction}
============================

The Data Catalog Vocabulary (DCAT) [[!VOCAB-DCAT-3]] is a W3C Recommendation that provides a standardised, machine-readable way to express information related to data catalogs published on the Web.
It enables data publishers to describe datasets and data services in a catalog using a standard model and vocabulary that facilitates the consumption and aggregation of metadata from multiple catalogs.

While this standard focuses on the cataloguing of datasets and related data services, it can be extended to incorporate other types of resources via the `dcat:Resource` class, which is an extension point for defining a catalog of any kind of resources.
As such, in this specification, we extend the DCAT standard with concepts to define catalogs of data usage conditions, i.e., [=Policies=].

In this context, the Policy Catalog (PolicyCAT) specification aims to define a standardised format for collections of policies, focusing in the management, description, and reusability of different types of access and usage control policies.
These catalogs can then include metadata such as the name, description, temporal stamps, and include references to specific data elements, purposes, and user groups involved in each policy.
Moreover, by implementing this specification, data publishers and consumers allow individuals and companies to define different data usages conditions profiles and apply them to specific types of data.

Besides DCAT, the DCMI Metadata Terms Recommendation [[!DCTERMS]] is also used to specify catalog metadata such as issuance and update dates, as well as information related to policy publishers and creators.

## Terminology ## {#terminology}

The following terms are used to describe concepts in this specification. 

<dl>
  <dt><dfn>Policies</dfn></dt>
  <dd>Data usage conditions that can be associated with any resource. Policies can include permissive, prohibitive and obligatory rules and can be limited by constraints, such as temporal or spatial restrictions, and duties, such as making a payment or a deleting an asset after using it.</dd>

  <dt><dfn>Policy Catalog</dfn></dt>
  <dd>A collection of policies, including metadata related to such policies.</dd>
</dl>

## Namespaces ## {#namespaces}

Commonly used namespace prefixes used in this specification:
```turtle
@prefix dcat:    <http://www.w3.org/ns/dcat#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix ex:      <http://example.org/> .
@prefix foaf:    <http://xmlns.com/foaf/0.1/> .
@prefix odrl:    <http://www.w3.org/ns/odrl/2/> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos:    <http://www.w3.org/2004/02/skos/core#> .
@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .
```

Main Entities {#main-entities}
==============================

## Catalog ## {#catalog}

`dcat:Catalog` is used to record metadata related to a collection of resources, including descriptions, temporal stamps, information about the entity that publishes the catalog, and so on. As such, in the context of this specification, it is used to record metadata related to a catalog of policies. A description of a catalog is shown below:

```turtle
ex:policy-catalog-001 a dcat:Catalog ;
  dcterms:title "Policy Catalog 001"@en ;
  dcterms:description "Catalog published by policy provider X, in English, with policies related to health data sharing"@en ;
  foaf:homepage <http://example.org/catalog/policy> ;
  dcterms:publisher ex:policy-provider-x ;
  dcterms:language <http://id.loc.gov/vocabulary/iso639-1/en>  ;
  dcat:themeTaxonomy ex:health-data ;
  dcat:resource ex:policy-001 , ex:policy-002 , ex:policy-003 .
```

`dcterms:title` and `dcterms:description` should be used to specify the name and provide a description of the catalog.
Moreover, `dcterms:publisher` should be used to identify the publisher of the catalog.
`foaf:homepage` and `dcterms:language` can be used to associate a catalog with a Web page where it is available and to describe the language of the policies in the Catalog, respectively.

The `dcat:themeTaxonomy` property should be used to classify the catalog's policies according to a set of domains represented by the relative IRI `ex:health-data`. As such, it can be used to include references to specific data elements, purposes, and user groups involved in the policies of the catalog, using the SKOS vocabulary [[!SKOS-REFERENCE]] to describe them. For instance, the example below defines `ex:health-records` and `ex:healthcare-provision` as being part of the set of domains of the theme taxonomy `ex:health-data` that describes the `ex:policy-catalog-001` policy catalog.

```turtle
ex:health-data a skos:ConceptScheme ;
  skos:prefLabel "A set of domains to classify the health data sharing policies in the catalog"@en .

ex:health-records a skos:Concept ;
  skos:inScheme ex:health-data ;
  skos:prefLabel "Health record data"@en .

ex:healthcare-provision a skos:Concept ;
  skos:inScheme ex:health-data ;
  skos:prefLabel "Healthcare service provision"@en .
```

Note: `odrl:hasPolicy` can be used to associate the catalog with its usage conditions using an ODRL conformant policy [[!ODRL-MODEL]]. Similarly, it can also be used for resources with the same goal.

Note: Versioning of catalogs can be done using `dcat:version`, `dcat:previousVersion`, `dcat:hasVersion`, and `dcat:hasCurrentVersion`. Analogously, it can also be used to version resources such as policies.

Issue: Mention the possibility of using DPV terms to describe domains related to the policies.

## Resource ## {#resource}

The catalog lists each of its resources via the `dcat:resource` property. A possible description of a policy resource using DCAT is shown below:

```turtle
ex:policy-001 a dcat:Resource ;
  dcterms:title "Policy 001"@en ;
  dcterms:description "Policy 001"@en ;
  dcterms:creator ex:employee-001 ;
  dcterms:issued "2011-12-05"^^xsd:date ;
  dcterms:modified "2011-12-15"^^xsd:date ;
  dcat:contactPoint <http://example.org/employee-001/contact> ;
  dcterms:conformsTo <http://www.w3.org/ns/odrl/2/> ;
  dcterms:publisher ex:lab ;
  dcterms:language <http://id.loc.gov/vocabulary/iso639-1/en> ;
  dcat:theme ex:health-records, ex:healthcare-provision ;
  dcat:distribution ex:policy-001-ttl .
```

The policy publication and revision dates are shown in `dcterms:issued` and `dcterms:modified`.
`dcterms:accrualPeriodicity` can be used to represent the frequency of update of the policy.
Furthermore, the temporal validity of the policy can be given using the `dcterms:temporal` property, defining a `dcterms:PeriodOfTime` as a closed interval indicated by `dcat:startDate` and `dcat:endDate`.

The properties `dcterms:creator` and `dcterms:publisher` should be used to define the entity responsible for producing the resource and the entity responsible for making the resource available, respectively.
Additionally, the `dcat:contactPoint` property can be used to provide the contact details of such entities.

`dcterms:conformsTo` should be used to indicate the standard or specification that the policy representation conforms to.
In the example above, `ex:policy-001` states that the mentioned policy conforms to the ODRL standard [[!ODRL-MODEL]].

`dcat:theme` is used to describe the themes or domains related to the described policy.
For instance, `ex:policy-001` is classified under the domains represented by the relative IRI `ex:health-records` and `ex:healthcare-provision`, which are part of the concept scheme identified by the IRI `ex:health-data` that was used to describe the catalog domains.

Finally, different representations of the policy `ex:policy-001` can be linked using the `dcat:distribution` property. The example above includes a distribution in the `.ttl` format.

Issue: `dcat:distribution` has domain `dcat:Dataset` and range	`dcat:Distribution`, so a similar property will need to be defined in this specification to associate policies with different distributions.

Issue: add a specific class and property, subclassing from `dcat:Resource` and `dcat:resource`, for policy resources, as these abstract concepts are not meant to be used.

## Distribution ## {#distribution}

`dcat:Distribution` represents an accessible form of a dataset such as a downloadable file.

```turtle
ex:policy-001-ttl a dcat:Distribution ;
  dcterms:title "TTL distribution of policy 001"@en ;
  dcterms:description "TTL distribution of policy 001"@en ;
  dcterms:issued "2011-12-05"^^xsd:date ;
  dcterms:modified "2011-12-15"^^xsd:date ;
  dcat:downloadURL <http://example.org/policy/001.ttl> ;
  dcat:mediaType <https://www.iana.org/assignments/media-types/text/turtle> .
```

Besides using DCMI Metadata Terms properties, such as `dcterms:description` or `dcterms:issued`, to add descriptions or temporal aspects of the distribution, `dcat:downloadURL` should be used to provide the downloadable policy file in a given format, indicated via the `dcat:mediaType` property.

## Agents ## {#agents}

DCAT uses `foaf:Agent`, and its sub-classes `foaf:Person` (for people) and `foaf:Organization` (for government agencies or other entities) to represent entities that create and publish catalogs and their resources.

```turtle
ex:policy-provider-x a foaf:Organization ;
  foaf:name "Policy Provider"@en .
```

Issue: Mention the possibility of using DPV terms to describe entities.

Vocabulary specification {#vocabulary}
======================================

TODO

Examples {#examples}
======================================

TODO